---
# yaml-language-server: $schema=https://www.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: technitium_exporter
  title: technitium_exporter
  description: Prometheus exporter for Technitium DNS Server
  annotations:
    backstage.io/source-location: url:https://github.com/donaldgifford/technitium_exporter
    backstage.io/techdocs-ref: "dir:."
  tags:
    - go
  namespace: default
spec:
  lifecycle: production
  type: service
  owner: donaldgifford
  system: dev-tools
