---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@v3
        with:
          extra_args: --results=verified,unknown
